### ISSUE TITLE
Fix logger reporting

### ISSUE THREAD

**Issue by virtser** [dorbel-tech/dorbel-shared#13]
When using dorbel-shared module as dependency from other projects, all logs written by dorbel-shared modules are not reported to log of the running app.

**Comment by virtser** [comment]
@avnersorek can you please take a look on it?
Its hard to work without logs sometimes.. 🇹🇷

**Comment by avnersorek** [comment]
fixed in https://github.com/dorbel-tech/dorbel-shared/pull/19
