### ISSUE TITLE
Implement clustering

### ISSUE THREAD

**Issue by virtser** [dorbel-tech/dorbel-shared#15]
Implement clustering using: https://www.npmjs.com/package/throng

**Comment by virtser** [comment]
Need to understand if that still make sense while running in Docker container.
Instead we can accomplish the same by running the same Docker container number of times on same machine.

**Comment by avnersorek** [comment]
yes even you just run 1 child of the cluster you still get much quicker
restart in case of crash

**Comment by virtser** [comment]
@avnersorek do you think it's a must for initial release?

**Comment by avnersorek** [comment]
Yes

**Comment by virtser** [comment]
See if more industry standard alternative is a better option: https://github.com/Unitech/pm2

**Comment by virtser** [comment]
Refer to clustering title in this post talking about pm2 clustering with Docker;
https://www.sitepoint.com/node-js-best-practices-from-the-node-gurus/?utm_source=nodeweekly&utm_medium=email#scaleup
