### ISSUE TITLE
Implement auth0 requests caching

### ISSUE THREAD

**Issue by virtser** [dorbel-tech/dorbel-shared#20]
Relevant for:
* Getting a Token for working with API.
* Getting user details from API.

Refer to /utils/userManagement.js

**Comment by avnersorek** [comment]
Redis good for this ? 
We can use docker for local and ElasticCache for prod

**Comment by virtser** [comment]
Yeah, sounds good. That's what I thought.

**Comment by virtser** [comment]
Inspiration article:
https://community.risingstack.com/redis-node-js-introduction-to-caching/

**Comment by virtser** [comment]
Setup ElasticCache Redis for test/stage environments.
