### ISSUE TITLE
Update Segment.io when user details are updated

### ISSUE THREAD

**Issue by avnersorek** [dorbel-tech/dorbel-shared#26]
They will be synced every login, but need to be updated if something happens during the session.
Should be done in user-management.

**Comment by virtser** [comment]
What is the library/api call should be used to update it?

**Comment by avnersorek** [comment]
The module is - https://segment.com/docs/sources/server/node/
The ``identify`` method should be used to update user details.
See the mapping to our schema here : https://github.com/dorbel-tech/auth0-rules/blob/master/rules/segmentIoSync.js

**Comment by avnersorek** [comment]
handled in https://github.com/dorbel-tech/dorbel-shared/pull/28

**Comment by virtser** [comment]
Can we close this issue?

**Comment by avnersorek** [comment]
yes
