### ISSUE TITLE
Move Segment client to shared

### ISSUE THREAD

**Issue by virtser** [dorbel-tech/dorbel-shared#27]
From: https://github.com/dorbel-tech/dorbel-app/notifications-service/src/sender/segmentClient.js
To let other service track events.

**Comment by avnersorek** [comment]
handled in https://github.com/dorbel-tech/dorbel-shared/pull/28

**Comment by virtser** [comment]
@avnersorek including deletion of notifications-service/src/sender/segmentClient.js and using of tracking from dorbel-shared module?

**Comment by avnersorek** [comment]
nope not yet, that PR was just for the dorbel-shared repository
