### ISSUE TITLE
domainErrors are not reported to log

### ISSUE THREAD

**Issue by virtser** [dorbel-tech/dorbel-shared#75]
https://github.com/dorbel-tech/dorbel-shared/blob/master/src/utils/domainErrors.js

**Comment by avnersorek** [comment]
IMHO The logging should be where the error is caught - error-handler middleware or something like that

**Comment by virtser** [comment]
Yes, but now in case of city/neighbourhoods mismatch, only user receives this error on client side and we don't know about it. 
Maybe domainErrors is not the place, but we need to report such cases so we can be aware of them..

**Comment by avnersorek** [comment]
yep city/neighbourhoods mismatch should not be a regular ValidationError
since it's not just bad user input.
